version: "3.8"

services:
  api:
    container_name: recipe-api-container
    build: .
    image: recipeapp:1.0
    environment:
      ENV_NAME: development
    ports:
      - "3333:3333"
    restart: unless-stopped
